name: Deploy to Server

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh -i "jenkins1.pem" ec2-user@ec2-3-111-52-137.ap-south-1.compute.amazonaws.com 'cd /var/www/html && git pull'
