name: Deploy to Server

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@server_ip 'cd /path/to/repository && git pull'
